### ISSUE TITLE
Training code of OV-COCO

### ISSUE THREAD

**Issue by Parsifal133** [xiaofeng94/SAS-Det#1]
Thank you for your awesome work and open source code!

I am very interested in the application of self-learning in open vocabulary, and trying to reproduce your work and experimental results on COCO-OVD.

Can you provide the training code of COCO-OVD?

**Comment by xiaofeng94** [comment]
Hey @Parsifal133 , Thanks for the interest. The release of training code is not approved by NEC Laboratories America, Inc. due to the internal usage.

But you may try to add the following block into `test_net.py` and refer to [RegionCLIP](https://github.com/microsoft/RegionCLIP/tree/main) on how to start training. 

```
    """
    If you'd like to do anything fancier than the standard training logic,
    consider writing your own training loop (see plain_train_net.py) or
    subclassing the trainer.
    """
    trainer = Trainer(cfg)
    trainer.resume_or_load(resume=args.resume)
    if cfg.TEST.AUG.ENABLED:
        trainer.register_hooks(
            [hooks.EvalHook(0, lambda: trainer.test_with_TTA(cfg, trainer.model))]
        )
    if cfg.MODEL.OVD.USE_PERIODIC_UPDATE:
        trainer.register_hooks(
            [hooks.CallbackHook(after_step=periodic_update_teacher)]
        )
    return trainer.train()
 ```

**Comment by Parsifal133** [comment]
What a pity!

But it is great anyway, I will try your suggestions, thanks again and wish you all the best!

**Comment by JinJin19991202** [comment]
> What a pity!
> 
> But it is great anyway, I will try your suggestions, thanks again and wish you all the best!

Hello, I’m extremely interested in the SAS-Det work. I noticed in the that you’ve successfully reproduced the authors’ implementation. However, I observed that the original authors did not provide the training scripts or configuration files. I use my writed code always error, and all AP be 0 or low. 

Would it be possible for you to share your reproduction code, including:
1. The training script (e.g., `train.py`)
2. Configuration files (e.g., YAML/JSON/Python config)

Your help would be greatly appreciated! If sharing is restricted, could you kindly guide me on how to adapt the original code for training?

Thank you very much for your time and effort!!
