### ISSUE TITLE
Question about Model Weight

### ISSUE THREAD

**Issue by Parsifal133** [xiaofeng94/SAS-Det#2]
Hi, @xiaofeng94 !  I got a few more question about `MODEL.WEIGHT`.

I use `./pretrained_ckpt/sas_det/sas_det_coco.pth` as `MODEL.WEIGHT` for training. The loss throughout the process is around 0.3, and there is no significant fluctuation. It seems that `./pretrained_ckpt/sas_det/sas_det_coco.pth` is the final trained model you provided. 

So I deleted `MODEL.WEIGHT` and used the following script to train the model on COCO :
```bash
python3 ./train_net.py \
    --num-gpus 1 \
    --config-file ./sas_det/configs/ovd_coco_R50_C4_ensemble_PLs.yaml \
    MODEL.CLIP.OFFLINE_RPN_CONFIG ./sas_det/configs/regionclip/COCO-InstanceSegmentation/mask_rcnn_R_50_C4_1x_ovd_FSD.yaml \
    MODEL.CLIP.BB_RPN_WEIGHTS ./pretrained_ckpt/rpn/rpn_coco_48.pth \
    MODEL.CLIP.TEXT_EMB_PATH ./pretrained_ckpt/concept_emb/coco_48_base_cls_emb.pth \
    MODEL.CLIP.CONCEPT_POOL_EMB ./pretrained_ckpt/concept_emb/my_coco_48_base_17_cls_emb.pth \
    MODEL.CLIP.OPENSET_TEST_TEXT_EMB_PATH ./pretrained_ckpt/concept_emb/coco_65_cls_emb.pth \
    MODEL.ROI_HEADS.SOFT_NMS_ENABLED True \
    MODEL.ENSEMBLE.TEST_CATEGORY_INFO "./datasets/coco_ovd_continue_cat_ids.json" \
    MODEL.ENSEMBLE.ALPHA 0.3 MODEL.ENSEMBLE.BETA 0.7

```
After training for about 5K iterations, the model runs evaluation on testset, and got a result like this, that is only 24.8 AP on Person and ZERO AP on the others: 
![11c0982aa852eaa7be37891d3402559](https://github.com/xiaofeng94/SAS-Det/assets/55016754/d98013b2-2404-4ea1-bb6f-3a6ed431bb90)

And after training for about 10K  iterations, the model got a higher AP on Person(29.8), but still Zero AP for other classes:
![d1ecbd0c8127092bf968d1ebf1fdc4d](https://github.com/xiaofeng94/SAS-Det/assets/55016754/3963db5f-0d08-4b26-a23c-1c03aedc6e2d)

Later, the training was terminated for other reasons.
(I also noticed that RegionCLIP use a Pretrained model for training(`MODEL.WEIGHTS ./pretrained_ckpt/regionclip/regionclip_pretrained-cc_rn50.pth`), but haven't got time to test it)

I mean, are the above experimental results reasonable?
Looking forward to any possible suggestions you may have.

**Comment by Parsifal133** [comment]
I am runing a new training now with the RegionCLIP Pretrained model `./pretrained_ckpt/regionclip/regionclip_pretrained-cc_rn50.pth`, and the training loss seems much more reasonable.

**Comment by Parsifal133** [comment]
> I am runing a new training now with the RegionCLIP Pretrained model `./pretrained_ckpt/regionclip/regionclip_pretrained-cc_rn50.pth`, and the training loss seems much more reasonable.

after training for 60K iter, the AP is still low for all classes. (bs=16 * 1 GPU, lr=0.002/8)

**Comment by xiaofeng94** [comment]
> Hi, @xiaofeng94 ! I got a few more question about `MODEL.WEIGHT`.
> 
> I use `./pretrained_ckpt/sas_det/sas_det_coco.pth` as `MODEL.WEIGHT` for training. The loss throughout the process is around 0.3, and there is no significant fluctuation. It seems that `./pretrained_ckpt/sas_det/sas_det_coco.pth` is the final trained model you provided.
> 
> So I deleted `MODEL.WEIGHT` and used the following script to train the model on COCO :
> 
> ```shell
> python3 ./train_net.py \
>     --num-gpus 1 \
>     --config-file ./sas_det/configs/ovd_coco_R50_C4_ensemble_PLs.yaml \
>     MODEL.CLIP.OFFLINE_RPN_CONFIG ./sas_det/configs/regionclip/COCO-InstanceSegmentation/mask_rcnn_R_50_C4_1x_ovd_FSD.yaml \
>     MODEL.CLIP.BB_RPN_WEIGHTS ./pretrained_ckpt/rpn/rpn_coco_48.pth \
>     MODEL.CLIP.TEXT_EMB_PATH ./pretrained_ckpt/concept_emb/coco_48_base_cls_emb.pth \
>     MODEL.CLIP.CONCEPT_POOL_EMB ./pretrained_ckpt/concept_emb/my_coco_48_base_17_cls_emb.pth \
>     MODEL.CLIP.OPENSET_TEST_TEXT_EMB_PATH ./pretrained_ckpt/concept_emb/coco_65_cls_emb.pth \
>     MODEL.ROI_HEADS.SOFT_NMS_ENABLED True \
>     MODEL.ENSEMBLE.TEST_CATEGORY_INFO "./datasets/coco_ovd_continue_cat_ids.json" \
>     MODEL.ENSEMBLE.ALPHA 0.3 MODEL.ENSEMBLE.BETA 0.7
> ```
> 
> After training for about 5K iterations, the model runs evaluation on testset, and got a result like this, that is only 24.8 AP on Person and ZERO AP on the others: ![11c0982aa852eaa7be37891d3402559](https://private-user-images.githubusercontent.com/55016754/295086346-d98013b2-2404-4ea1-bb6f-3a6ed431bb90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTQ2MDcsIm5iZiI6MTcwNDg1NDMwNywicGF0aCI6Ii81NTAxNjc1NC8yOTUwODYzNDYtZDk4MDEzYjItMjQwNC00ZWExLWJiNmYtM2E2ZWQ0MzFiYjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAyMzgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5N2ZlYzRiODJiODBmNzExNzkyZmYxMDZlMTZkZTU0YzM1MDNiYjZhMDUyYjI2MGE4YWMwNjAxZjUxNzRhMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.akVbQ9kDmfW8kcabFeQP9awOk5f2GDK1gTidqnC2iwQ)
> 
> And after training for about 10K iterations, the model got a higher AP on Person(29.8), but still Zero AP for other classes: ![d1ecbd0c8127092bf968d1ebf1fdc4d](https://private-user-images.githubusercontent.com/55016754/295086082-3963db5f-0d08-4b26-a23c-1c03aedc6e2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTQ2MDcsIm5iZiI6MTcwNDg1NDMwNywicGF0aCI6Ii81NTAxNjc1NC8yOTUwODYwODItMzk2M2RiNWYtMGQwOC00YjI2LWEyM2MtMWMwM2FlZGM2ZTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAyMzgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZmNjNTdjMzg0YWIxNmU4NWYyMGM3NmFjNzI4ODgwYTIxMWU2NjI2NzIzYzVkZTg3YjNmOTQyYmQ4NDIzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VdLbnk-0mOseURcUdh0_F6Xk_hQQ4b9A6nMcgbvTSNM)
> 
> Later, the training was terminated for other reasons. (I also noticed that RegionCLIP use a Pretrained model for training(`MODEL.WEIGHTS ./pretrained_ckpt/regionclip/regionclip_pretrained-cc_rn50.pth`), but haven't got time to test it)
> 
> I mean, are the above experimental results reasonable? Looking forward to any possible suggestions you may have.

Hey, this is not normal. You may check your data. Probably, you somehow get the data that only contains one category (Person). 

BTW, you can also check if you get reasonable PLs using [this function](https://github.com/xiaofeng94/SAS-Det/blob/fd6ea7dc2ba07d3a836b5e65bdd0fd57bd60cb9c/sas_det/modeling/meta_arch/clip_rcnn.py#L312). It's revoked somewhere in the model forward during training.

**Comment by Parsifal133** [comment]
MODEL.WEIGHT is not necessary for training, right?

I prepared the data according to the instructions of RegionCLIP and directly tested the weights you provided. 
There was no obvious difference between the test results and the data in your paper.

**Comment by xiaofeng94** [comment]
MODEL.WEIGHT should be used. 

I used [this weight](https://drive.google.com/file/d/1D0EcusSzLxxKwQ6JpqCpJ4jwPm6Swh1g/view?usp=drive_link) (I follow RegionCLIP's pretraining but with COCO-base boxes only) or RegionCLIP weights to init the model. If you want to other weights, please check the customized [ load_state_dict](https://github.com/xiaofeng94/SAS-Det/blob/fd6ea7dc2ba07d3a836b5e65bdd0fd57bd60cb9c/sas_det/modeling/meta_arch/clip_rcnn.py#L282). The current one may not load the weights as you want.

**Comment by Parsifal133** [comment]
> MODEL.WEIGHT should be used.
> 
> I used [this weight](https://drive.google.com/file/d/1D0EcusSzLxxKwQ6JpqCpJ4jwPm6Swh1g/view?usp=drive_link) (I follow RegionCLIP's pretraining but with COCO-base boxes only) or RegionCLIP weights to init the model. If you want to other weights, please check the customized [ load_state_dict](https://github.com/xiaofeng94/SAS-Det/blob/fd6ea7dc2ba07d3a836b5e65bdd0fd57bd60cb9c/sas_det/modeling/meta_arch/clip_rcnn.py#L282). The current one may not load the weights as you want.

Got it, I'll try it again

**Comment by Parsifal133** [comment]
Finally， I got a normal result after use [this weight](https://drive.google.com/file/d/1D0EcusSzLxxKwQ6JpqCpJ4jwPm6Swh1g/view?usp=drive_link).

Thanks again!
 Good luck with your paper. (Must be CVPR or something, I guess)

**Comment by meilijunxi** [comment]
> > I am runing a new training now with the RegionCLIP Pretrained model `./pretrained_ckpt/regionclip/regionclip_pretrained-cc_rn50.pth`, and the training loss seems much more reasonable.
> 
> after training for 60K iter, the AP is still low for all classes. (bs=16 * 1 GPU, lr=0.002/8)

What GPU did you use? How much memory does it occupy during training?

**Comment by Parsifal133** [comment]
@meilijunxi 
I used one NVIDIA A800(80GB) card. With Automatic mixed precision training and bs=8, it occupied nearly 40G of GPU memory.

**Comment by wkfdb** [comment]
hey, I went into some problem when running trainer.train(). At the evaluation step, it always stuck after printing "Start inference on 1209 batches". Do you ever meet the same problem? 
![啊的风口浪尖阿斯利康JFK拉升阶段利夫卡弗](https://github.com/xiaofeng94/SAS-Det/assets/22614640/03b63563-90a6-4f7d-a93d-9bf02604bd10)

**Comment by wkfdb** [comment]
It just stucks. And I really dont know why it happen, even after carefully reading the source code of the Trainer.

**Comment by wkfdb** [comment]
Well well well, it turns out to be the DATALOADER.NUM_WORKERS in cfg. I set this argument as 0 and the evaluation never stucks.

**Comment by Parsifal133** [comment]
Excuse me! @xiaofeng94 , I am currently reproducing the experiments on  LVIS,  and i want to confirm if the pre-trained weights you used are `regionclip_finetuned-lvis_rn50.pth` and `regionclip_finetuned-lvis_rn50x4.pth` provided by Region-CLIP.(https://drive.google.com/drive/folders/1YTiJJ4sAqHGj-_viiUyuADOdvlHsoub9)

Because I trained with `regionclip_finetuned-lvis_rn50.pth` for 80K iterations, but the AP metrics are lower than expected.

**Comment by Parsifal133** [comment]
The training loss is decreasing as expected, but the AP metrics (both novel and base) do not show an upward trend after testing. 
The only changes I made were： not training the mask head， and using mixed precision training.

And i previously tested `sas_det/sas_det_lvis_r50.pth` weights you provided, and the AP metrics matched those reported in the paper. This should indicate that the data is not the issue.

**Comment by Parsifal133** [comment]
I double-checked the output logs and noticed that the weights provided by Region-CLIP do not seem to load automatically into the teacher model. I am currently trying to modify the loading function.

**Comment by xiaofeng94** [comment]
Hey @Parsifal133 , I used `regionclip_pretrained-cc_rn50.pth` and `regionclip_pretrained-cc_rn50x4.pth`. They're pretrained on CC3M, which may provide better alignment between vision and language.

BTW, if you observe AP for base categories does not increase during training, there is very likely something wrong in the code.

**Comment by Parsifal133** [comment]
Thank you for your detailed response! I will try using the weight `regionclip_pretrained-cc_rn50.pth` again.

**Comment by Parsifal133** [comment]
Hi @xiaofeng94 , I've been troubleshooting recently and noticed that fast_rcnn/false_negative allways be 1, while fast_rcnn/fg_cls_accuracy is 0. This indicates that the student model's predictions are completely wrong. I also observed that the ROI head is selecting very few positive samples (less than 10). I realized this might be related to the RPN, so I manually loaded the pre-trained RPN weights during training (the ones you provided). After loading, the ROI now selects around 50 positive samples (seemingly normal), but fast_rcnn/false_negative is still 1.

It looks like the student model hasn't been trained correctly, but I visualized the GT and pseudo-labels, and they both appear to be correct.

Could you provide some possible solutions?
![4167ea51905cb6115baae03d106c918](https://github.com/user-attachments/assets/46d2ca4e-9bde-4ea3-980c-f5713ab88800)

**Comment by Parsifal133** [comment]
I also noticed that LVIS is a federated dataset, meaning not all instances are annotated (e.g., many “people” objects in the images are not labeled). 

Does this imply that it will be challenging to reproduce LVIS's experimental results by following the previous COCO training pipeline?

**Comment by xiaofeng94** [comment]
> Hi @xiaofeng94 , I've been troubleshooting recently and noticed that fast_rcnn/false_negative allways be 1, while fast_rcnn/fg_cls_accuracy is 0. This indicates that the student model's predictions are completely wrong. I also observed that the ROI head is selecting very few positive samples (less than 10). I realized this might be related to the RPN, so I manually loaded the pre-trained RPN weights during training (the ones you provided). After loading, the ROI now selects around 50 positive samples (seemingly normal), but fast_rcnn/false_negative is still 1.
> 
> It looks like the student model hasn't been trained correctly, but I visualized the GT and pseudo-labels, and they both appear to be correct.
> 
> Could you provide some possible solutions? ![4167ea51905cb6115baae03d106c918](https://private-user-images.githubusercontent.com/55016754/359425388-46d2ca4e-9bde-4ea3-980c-f5713ab88800.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NDM0MDIsIm5iZiI6MTcyNDQ0MzEwMiwicGF0aCI6Ii81NTAxNjc1NC8zNTk0MjUzODgtNDZkMmNhNGUtOWJkZS00ZWEzLTk4MGMtZjU3MTNhYjg4ODAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE5NTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZGNiMTM5YWI3ZTVhYWFhY2NiMjQ2MTQ0ZDYyZDhjMjczNjg4ZDc4NWRiMTRkNjM1M2Q2ZTc2NzBkNmEyMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tYKTHXFoBA-5gwP_T0jpt-DGyHv2G3JiQ_h_KPMSJ_E)

Hey @Parsifal133, I don't know what cause the problem. But you may check the RPN for fg_cls_accuracy.
For LVIS, we do use a different RPN. See [here](https://github.com/xiaofeng94/SAS-Det?tab=readme-ov-file#results-on-lvis-ovd)

**Comment by Parsifal133** [comment]
Thank you, the fg classification accuracy during training has now increased to around 50% (after 40k iterations). 

However, the mAP during testing is extremely low. I visualized the inferred objects and found that most of them are misclassified. I noticed that a different text embedding `self.test_cls_score.weight` was used during testing. 
And i found that if use the `self.image_head_concepts` (embedding from training) during testing, the objects are correctly classified. 

Could this be happening because the model hasn’t been fully trained?

**Comment by JinJin19991202** [comment]
> Hi [@xiaofeng94](https://github.com/xiaofeng94) , I've been troubleshooting recently and noticed that fast_rcnn/false_negative allways be 1, while fast_rcnn/fg_cls_accuracy is 0. This indicates that the student model's predictions are completely wrong. I also observed that the ROI head is selecting very few positive samples (less than 10). I realized this might be related to the RPN, so I manually loaded the pre-trained RPN weights during training (the ones you provided). After loading, the ROI now selects around 50 positive samples (seemingly normal), but fast_rcnn/false_negative is still 1.
> 
> It looks like the student model hasn't been trained correctly, but I visualized the GT and pseudo-labels, and they both appear to be correct.
> 
> Could you provide some possible solutions? ![4167ea51905cb6115baae03d106c918](https://github.com/user-attachments/assets/46d2ca4e-9bde-4ea3-980c-f5713ab88800)

Hi @Parsifal133 ，Did you solve this problem? I'm having the same issue now and have no idea how to deal with it. Could you share your solution? Thank you so much!
