### ISSUE TITLE
Questions about the ‘open vocabulary’ task

### ISSUE THREAD

**Issue by 2580023853** [xiaofeng94/SAS-Det#3]
Thanks for your great work, but I have some questions regarding the task setup in this paper. Does the open concept mentioned in the paper correspond to the novel categories in the dataset? If so, does this mean that, according to the definition of "open vocabulary" in this paper, the names of novel categories are known, while the labels are unknown?

**Comment by xiaofeng94** [comment]
Hey, thanks for your interest in this paper. 

The answer is YES. This setting is more like zero-shot object detection. You may see more discussion in settings for OVD in ``Object-Aware Distillation Pyramid for Open-Vocabulary Object Detection``. 
BTW, SAS-Det also works on categories that are not known for pseudo label generation. Check Table 6 of our paper.
